; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
upload_speed = 921600
upload_protocol = teensy-gui
extra_scripts = copy_hex.py
build_flags = 
    ; -DENABLE_ISOBUS_VT  ; Uncomment to enable ISOBUS VT (requires reduced features elsewhere)
lib_deps = 

; ISOBUS build with web server moved to flash memory
[env:teensy41-isobus]
platform = teensy
board = teensy41
framework = arduino
upload_speed = 921600
upload_protocol = teensy-gui
extra_scripts = copy_hex.py
build_flags = 
    -DENABLE_ISOBUS_VT
    -DWEBSYSTEM_USE_FLASHMEM
lib_deps = 

; ISOBUS build with minimal features (no web server)
[env:teensy41-isobus-minimal]
platform = teensy
board = teensy41
framework = arduino
upload_speed = 921600
upload_protocol = teensy-gui
extra_scripts = 
    pre:teensy41_isobus.py
    copy_hex.py
build_flags = 
    -DENABLE_ISOBUS_VT
    -DDISABLE_WEB_SERVER
    -DDISABLE_SERIAL_MENU
    -DDISABLE_REMOTE_SWITCH
    -DDISABLE_SPEED_PULSE
    -ffunction-sections
    -fdata-sections
build_unflags = 
    -flto
lib_deps = 
